### ISSUE TITLE
RPI Audio Streaming?

### ISSUE THREAD

**Issue by frogg** [kclyu/rpi-webrtc-streamer#1]
First of all, great project! I was wondering if it is also possible to transfer audio streams using WebRtc on the Raspberry PI using your framework. I couldn't find anything related to audio streaming in your documentation.

**Comment by kclyu** [comment]
Thank you for your praise. Basically, the audio part is supposed to use the linux support part of the webrtc native code, and expect that the webrtc native linux code will work if there is no big problem. The audio part is going to be scheduled after some other high priority parts (TCP direct channel, websocket supports, video stream QoS) have progressed.

**Comment by kclyu** [comment]
Please refer to the this [README_audio.md](https://github.com/kclyu/rpi-webrtc-streamer/blob/master/README_audio.md)
