### ISSUE TITLE
rasbperry pi zero W ninja build problem

### ISSUE THREAD

**Issue by adrian23** [kclyu/rpi-webrtc-streamer#10]
Hi,
`when i try to build webrtc for ~/Workspace/rpi-webrtc-streamer/misc/webrtc_armv6_build_args.gn`
after 
`ninja -C arm_build` i got error` :
[ninja build problem.txt](https://github.com/kclyu/rpi-webrtc-streamer/files/1202755/ninja.build.problem.txt)

Can you check if this build conf is correct and work with newest webrts ?

Thanks

**Comment by kclyu** [comment]
Hi, 
I get the same error. 
If you are not using OPUS,   Building without opus module seems to be the fastest way. 
Currently, OPUS for armv6 seems to have an issue with building. (ARM neon does not have the same issue).

To exclude the opus from building, add the following two lines to args.gn:
 
rtc_build_opus=false
rtc_include_opus=false

**Comment by adrian23** [comment]
HI,
thanks yes it solve prlbem thankyou
