### ISSUE TITLE
stream multiple CSI cameras

### ISSUE THREAD

**Issue by jonspieg** [kclyu/rpi-webrtc-streamer#101]
First of all this is a great project!
I have a rpi compute module 3+ with two CSI cameras connected.
Is there a way to choose which camera is being used in RWS?
I would Ideally run two instances of RWS on different ports, each streams a different camera.
Do you think this configuration could work?

Thanks!

**Comment by kclyu** [comment]
I never thought it would be used in a computer module. Currently, the camera Num is fixed. Even if you run the process separately, it seems that only the first camera will be used unless you change the camera Num.

It seems that I need to add configuration parameter related to camera num.

**Comment by jonspieg** [comment]
Adding this to the configuration will be awesome! 

For the meanwhile should changing this line in mmal_video.c do the trick? 
`state->cameraNum = 0;`
to:
`state->cameraNum = 1;`

or are there other places I need to address?

I'm trying to cross compile now and see how it goes.

**Comment by kclyu** [comment]
This is the version that config was added to media_config.conf with camera_select.
[webrtc-streamer.gz](https://github.com/kclyu/rpi-webrtc-streamer/files/4771700/webrtc-streamer.gz)

``` media_config.conf
camera_select=1
```
I haven't tested multiple processes using the mmal component, so I'm not sure if the two processes will work well at high resolution. I don't have a computer module, so there are limits to my own testing.

If the camera select is set to the wrong value, the following InitEncode shows the following error message.

```
(raspi_encoder_impl.cc:103): InitEncode
(raspi_quality_config.cc:174): BestMatch Resolution 320x240, for target bitrate: 300, moving factor: 1.8
(raspi_encoder_impl.cc:168): InitEncode request: 320 x 240
(mmal_wrapper.cc:275): InitEncoder 320x240@30, 300 kbps
(mmal_wrapper.cc:231): Created EncoderDelayedInit Task, Scheduling on queue...
(mmal_wrapper.cc:280): EncoderDelay Status changed from INIT_PASS to WAITING
(mmal_wrapper.cc:519): Start initialize the MMAL encode wrapper.320x240@30, 300kbps
mmal: Could not select camera : error 3
(mmal_wrapper.cc:538): Failed to create camera component
(mmal_wrapper.cc:1018): Failed to run camera app. Please check for firmware updates
mmal: mmal_port_parameter_set: no port
(mmal_wrapper.cc:917): Unable to unset capture start
(video_stream_encoder.cc:698): Failed to initialize the encoder associated with codec type: H264 (4)
(video_stream_encoder.cc:729): Failed to configure encoder.
```

**Comment by jonspieg** [comment]
This works great!

Now I'm able to run two instances of RWS each on a different port streaming a different camera!

Thanks again for this great project and for your specific help regarding this subject :)
