### ISSUE TITLE
README_building.md have mismatched raspios image file name

### ISSUE THREAD

**Issue by mikeqoo1** [kclyu/rpi-webrtc-streamer#110]
./build_rootfs.sh download file is `yyyy-mm-dd-raspios-buster-(armhf).zip' not `yyyy-mm-dd-raspbian-buster.zip`

**Comment by mikeqoo1** [comment]
![Uploading 123.png…]()

**Comment by mikeqoo1** [comment]
![123](https://user-images.githubusercontent.com/30303712/94223093-aaa27a80-ff21-11ea-8abd-e153121dca90.png)

**Comment by kclyu** [comment]
It has been fixed in a recent patch.
