### ISSUE TITLE
Increased binary size (rtc_use_h264=true)

### ISSUE THREAD

**Issue by ronb127** [kclyu/rpi-webrtc-streamer#114]
Hello,
In commit 4a64301c: "Source update for WebRTC Cr-Commit Position 31187" rtc_use_h264 was changed from 'false' to 'true'.
This causes an increase of 2-3 MB in binary size (ffmpeg is now compiled in webrtc).
If I build webrtc with "rtc_use_h264=false" then the binary size is reduced again, but H.264 is no longer offered in the SDP and the video stream doesn't work.
Can we somehow go back to "rtc_use_h264=false" (for smaller binary size) without disabling H.264, as it was before?
Thanks.

**Comment by kclyu** [comment]
For now, it seems difficult unless you modify the webrtc native code itself. By the way, it doesn't seem that the 2~3M increase is so sensitive, do you use it for other purposes?

**Comment by ronb127** [comment]
Just trying to keep my binaries small.
I wonder how it worked before, and what makes it fail now. ffmpeg is clearly unnecessary with external H.264 streams. Maybe I'll post a bug/request on webrtc forums.

**Comment by ronb127** [comment]
I was able to exclude ffmpeg from the build by applying a small patch to webrtc:
modules/video_coding/BUILD.gn
modules/video_coding/codecs/h264/h264.cc
See patch file: [h264.txt](https://github.com/kclyu/rpi-webrtc-streamer/files/5450321/h264.txt)
You should build with use_rtc_h264=true, only now ffmpeg is excluded and binary size is reduced.

**Comment by kclyu** [comment]
I will refer to it later when creating a new rws package. Thank you.
