### ISSUE TITLE
Is there some way to have multiple connections?

### ISSUE THREAD

**Issue by juniorsaldanha** [kclyu/rpi-webrtc-streamer#116]
Hi, i'd like to know if there is some way to have multiples connections on the same source video (raspicam TC358743), with only one connection work great, but i couldnt find an way to have multiples connections.

Here is the message that i received on web browser console:
![Captura de tela de 2020-11-23 13-39-57](https://user-images.githubusercontent.com/30378044/99989556-83d1ba80-2d91-11eb-99af-48ba32727691.png)

thnks , :+1:

**Comment by kclyu** [comment]
RWS itself does not support multiple rtp connections.

If you want to make multiple RTP connections, you should use it in  interworking with gateway functions such as videoroom supported by WebRTC gateway. 

Currently, I are developing a function to interwork with janus gatway's videoroom, and when it is completed, multiple RTP connections are possible.  For developments related to janus gateway development, please refer to  [Connect to Janus Gateway](#43)

**Comment by gunnarsundberg** [comment]
@kclyu are there any updates on integrating with Janus?
