### ISSUE TITLE
iOS 11 support

### ISSUE THREAD

**Issue by superddr** [kclyu/rpi-webrtc-streamer#16]
Hey this is an excellent work! I can finally watch my own room from work now ! So cool and I will probably control a remote car to move arround and follow my little baby.
Recently iOS 11 is released ,with WebRTC support , does any body know how to make it work on iphone? I'm working on it , still have no luck yet. Hope we can watch live video on iphone soon!

**Comment by superddr** [comment]
alright,i heard that chrome is using vp8 while apple is using h264, thats why the video wont show on iphone. is there any chance that we can use h264？

**Comment by superddr** [comment]
alright,i heard that chrome is using vp8 while apple is using h264, thats why the video wont show on iphone. is there any chance that we can use h264？

**Comment by kclyu** [comment]
In practice RWS also uses only H.264 codec. Codec support might be better suited.

I've tried a simple test but I have confirmed that the video is not yet available. Right now I spend most of my time on the motion detection function, so I have not been able to test it yet deeply.

I will let you know when it is tested or if there are other issues.

**Comment by superddr** [comment]
Hey good news! I finally figured it out. iOS just don't allow autoplay, so you have to manually start it by the controls. So the video tag has to be like this way: &lt;video playsinline controls />.  Now you can click the start button to start it.
