### ISSUE TITLE
Building WebRTC for Raspberry Pi Zero

### ISSUE THREAD

**Issue by vahid-dan** [kclyu/rpi-webrtc-streamer#20]
Hi;

In "Building RPi-WebRTC-Streamer in Ubuntu", what is the correct configuration in `arm_build/args.gn` for Raspberry Pi Zero? I guess the default configuration is for Raspberry Pi 3.

Thanks in advance.

Bests,
Vahid

**Comment by kclyu** [comment]
Hi, 
misc/webrtc_arm_build_args.gn is for arm7 and you can use Rpi2 or above.
And misc/webrtc_armv6_build_args.gn is armv6 args.gn for Rpi1 and Pi Zero.
Thanks, 
Lyu.

**Comment by vahid-dan** [comment]
Thank you very much. :-)
