### ISSUE TITLE
Deb file are not working

### ISSUE THREAD

**Issue by phdemartin** [kclyu/rpi-webrtc-streamer#23]
I know it's a work in progress, and thank you for you work on this project.
I've got an issue with the deb's:

> sudo dpkg -i rws_0.72.0_armhf.deb.1
> dpkg-deb: error: 'rws_0.72.0_armhf.deb' is not a debian format archive
> dpkg: error processing archive rws_0.72.0_armhf.deb (--install):
> subprocess dpkg-deb --control returned error exit status 2
> Errors were encountered while processing: rws_0.72.0_armhf.deb

**Comment by kclyu** [comment]
I can install it without problems. Check if there is a problem with the download.
```
pi@raspberrypi:~ $ sudo dpkg -i rws_0.72.0_armhf.deb 
Selecting previously unselected package rws.
(Reading database ... 141186 files and directories currently installed.)
Preparing to unpack rws_0.72.0_armhf.deb ...
Unpacking rws (0.72.0) ...
Setting up rws (0.72.0) ...
pi@raspberrypi:~ $ 
pi@raspberrypi:~ $ sha256sum rws_0.72.0_armhf.deb 
f66c83631f8606fe853e82f1d49dd32bd795865849ddc1612db3958320c5c9e0  rws_0.72.0_armhf.deb
pi@raspberrypi:~ $ 
```
