### ISSUE TITLE
How can I get video from webcam 

### ISSUE THREAD

**Issue by hawkhsieh** [kclyu/rpi-webrtc-streamer#26]
Could this project support a video source from a normal webcam? The dev path maybe /dev/video0.

**Comment by kclyu** [comment]
I think you're talking about V4l2. v4l2 support is required to run on other Linux hardware or to support USB cam on raspberry pi. However, this is not a supported feature right now.

**Comment by mikeqoo1** [comment]
hi, did you supported this feature now? 

thx
