### ISSUE TITLE
Ability to execute a python script if motion is detected

### ISSUE THREAD

**Issue by rexlow** [kclyu/rpi-webrtc-streamer#35]
Is it possible to define our own action? 

For instance, I would like to be able to execute a python script if a motion is detected.

**Comment by kclyu** [comment]
There is currently no ability to call python scripts directly from RWS or to pass events to other processes. The ability to deliver events  from rws will be planned after further enhancements to motion detection.

Currently, it is only possible to continuously monitor the directory where the motion file is stored and to deliver the event when a new video file is created. You can use [TelegramBot](https://github.com/kclyu/rpi-webrtc-streamer/blob/master/README_TelegramBot.md) and you can refer to it as an example.

**Comment by rexlow** [comment]
Thanks for the clarification. My application intends to capture and process feed if a motion is detected.  I guess I will have to create a python script to capture the feed through a socket connection instead, then only process the feed.
