### ISSUE TITLE
Running on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by cjprecord** [kclyu/rpi-webrtc-streamer#40]
Hello,

I was giving the pi zero deb package a try on my pi zero w and cant seem to get it running properly.

Configuration:
* Pi Zero W
* Pi Camera v2
* Pi running Stretch, no X Server
* Testing from ubuntu PC on LAN

RWS service starts and I am able to navigate to the native-peerconnection test page. When I start the connection I hear the speaker on my Pi click, then the Pi becomes very slow and unresponsive, with no video being transmitted to the browser on PC.

I have tried various settings and using low resolution and lower frame rate in the config files to same result.

Any advice on what I should look into to diagnosis this issue further?

Thanks

**Comment by kclyu** [comment]
Can you upload a log in the log directory?

If you have a problem after PI click sound, there seems to be a problem in audio play. After disabling all audio related settings, it is necessary to confirm that vidoe is normally operated.
If the video is straming normally, it should be tried to modify the audio-related settings one by one.
 

For reference, 73.2_RaspiZeoW deb file was confirmed to be video streaming operation in ZeroW jessie. 73.2 deb has been confirmed to work on jessie / stretch in PI2 / 3.
Thanks,
Lyu.

**Comment by cjprecord** [comment]
I had the audio_processing_enable in media_config.conf set to false already but tried again with the others also set to false with same result.

Pi CPU pegs out at 100% and doesn't stream anything. Think I will try on a fresh image if I can find time tomorrow.

Log from last try attached.

Thanks

[rws_log_0.gz](https://github.com/kclyu/rpi-webrtc-streamer/files/1981990/rws_log_0.gz)

**Comment by kclyu** [comment]
If you can not get the log message from the log file, you can see the log in the console in the following way.

```
sudo systemctl stop rws
cd /opt/rws/
./webrtc-streamer --verbose
```
Do not forget `sudo systemctl start rws` after checking the log.

**Comment by cjprecord** [comment]
I attached the log file in previous post, was it not correct?

edit: nevermind, sorry I am not sure what happened but the log file is empty. It looked like it was about 3MB when I was grabbing of the pi last night. Will try again this evening.

**Comment by kclyu** [comment]
The attached log size is 40 bytes. Maybe it's because you forced the process to kill or rebooting ...
When rws is restarted, the old log file is moved to the backup directory, and it looks like you sent a newly created rws_log_0.

**Comment by cjprecord** [comment]
Here is a log from running rws service. Closed out of the browser session on the remote pc and waited for rpi to get responsive again to get the log copied out this time.

[rws_log_0.gz](https://github.com/kclyu/rpi-webrtc-streamer/files/1986017/rws_log_0.gz)


Update: I retried on a fresh image of Stretch light and was successfully able to stream some video. So not sure but something must have gotten messed up on the image on the other SD card.

**Comment by kclyu** [comment]
RWS did not work with raspbian jessie lite. I have not tested it yet with the stretch lite version. It seems to be a little different from the previous one because you say it works.
Since jessie lite does not work, I recommend using stretch desktop rather than stretch lite if possible.

**Comment by cjprecord** [comment]
Ok, will give stretch desktop a try as well.

Have been able to get a few seconds of streaming with lite version and no longer any CPU overload on the rpi.

Still diagnosing if bandwidth issue or other problem as sometimes difficult to get webrtc session to start the stream to test. Can see the activity happen on the pi when starting connection on browser from PC.

**Comment by cjprecord** [comment]
Tried with fresh image of Stretch Desktop and got good results this time as long as the wifi signal is good it works quite well.

Thanks for the help
