### ISSUE TITLE
 Introduce the features of the application

### ISSUE THREAD

**Issue by zero863** [kclyu/rpi-webrtc-streamer#41]
sorry to bother you ,my English is poor, recently I'm working on RPI too, trying to make a Audio and video communication between two RPIs or RPI and PC, I want to know whether your application is samilar too? Can you explain it for me ? thank you very much.

**Comment by kclyu** [comment]
This repo is a project to stream Video & Audio from Rpi to PC or Smart phone browser or Mobile App using WebRTC. WebRTC is gooling out a lot of information. First, you might want to check what WebRTC is.
Please refer to README.md of this Repo for function related parts.
