### ISSUE TITLE
Is it possible to show video stream in android   phone browser ?

### ISSUE THREAD

**Issue by tigran1984** [kclyu/rpi-webrtc-streamer#46]

**Comment by kclyu** [comment]
The following browsers have been confirmed for streaming.
(Opera and Firefox have been tested a little bit long ago. I think it will work also)
Chrome - Android, IOS, Linux
Safari - IOS, MacOS
Opera - Android, Linux
FireFox - Android, Linux

**Comment by tigran1984** [comment]
Thanks for replying, I have another question is there a difference what version of android i am using, and is there minimum android version under of which is unsupportable.

**Comment by kclyu** [comment]
I do not manage minimum android and browser versions. I can not give you much help. And, it depends on the browser version rather than the android version, but it is better to use the latest version as possible.

**Comment by tigran1984** [comment]
OK thanks for answer.
