### ISSUE TITLE
How I can show raspberry pi stream in not local network?

### ISSUE THREAD

**Issue by tigran1984** [kclyu/rpi-webrtc-streamer#47]

**Comment by kclyu** [comment]
Currently, there is no support for setting https within RWS. You can use https and reverse proxy with nginx or apach additionally, but there is no user management part, so you have to use it with caution. It is recommended to use the VPN of the Internet router you are using for easy use.

Please refer to [README_rws_setup](https://github.com/kclyu/rpi-webrtc-streamer/blob/master/README_rws_setup.md) for setting method and other documents.
