### ISSUE TITLE
Direct video stream

### ISSUE THREAD

**Issue by RoncoRimini** [kclyu/rpi-webrtc-streamer#48]
I installed rws on a RPI 3, the native peer connection works like a charm!
I need to read the video stream with OpenCV in a Windows c# application and in a Linux c++ application, is it possible to have a direct stream (similar in example to a RSTP stream) that can be directly read from OpenCV?

**Comment by kclyu** [comment]
OpenCV does not yet have the ability to receive and use WebRTC's SRTP directly. Currently, you must write your own C ++ code or C# code using the WebRTC native code package and pass the video frame directly to OpenCV.

If you want to develop it yourself, it may be helpful to use src/examples/peerconnection/client code after downloading [WebRTC package code package](https://webrtc.org/native-code/development/).
