### ISSUE TITLE
Changing camera configuration in run-time

### ISSUE THREAD

**Issue by tovil** [kclyu/rpi-webrtc-streamer#53]
Hi,
Is it possible to change some camera parameters during run-time?
For example, controlling the brightness, exposure, etc.

**Comment by kclyu** [comment]
Currently only supported in config file configuration. However, since proxy_interface now includes the ability to change media-related settings at runtime, it is available when proxy_interface development is complete.

**Comment by tovil** [comment]
Thanks. 
Looking forward to it
