### ISSUE TITLE
streaming video file in storage.

### ISSUE THREAD

**Issue by HwangJeMin** [kclyu/rpi-webrtc-streamer#57]
Hello, thank you for nice work.

i succeed streaming build, and can play video of rpiCam

but I want to streaming my own video file using 'rpi-webrtc-streamer'.

is it possible?

**Comment by HwangJeMin** [comment]
another question..

i captured streaming packet and checked video data is transferred through UDP.

can i choose transfer protocol TCP or UDP?

**Comment by kclyu** [comment]
-  Streaming the video in the local storage 
The feature to stream local storage files is not yet supported. This feature is still a low priority compared to other features and seems to need a little more.

- RTP over TCP
Please refer to the following [Force TCP for WebRTC Peerconnection](https://stackoverflow.com/questions/35062682/force-tcp-for-webrtc-peerconnections) for 'RTP over TCP'. I already answered,

**Comment by HwangJeMin** [comment]
thank you for answer!
