### ISSUE TITLE
Will I be able to stream videos from B101 HDMI to CSI-2 Bridge?

### ISSUE THREAD

**Issue by msbasanth** [kclyu/rpi-webrtc-streamer#61]
Hi,

I have RPi connected to B101 HDMI to CSI bridge and I could get the HDMI video stream when I connect a video source to it (raspivid -t 0). Whether I can use RWS for streaming the video output which is in H264 format using WebRTC?

My usecase is just to stream that video to one user over HTTP may be to RWS front end. Whether I can use RWS in such usecase?

Regards
Basanth

**Comment by kclyu** [comment]
It is a little ambiguous to tell you whether or not it will work. 
Try it without changing any settings in RWS  and If it does not work, try to  use fixed resolution and FPS at 1080p@25. 
If there is a delay on the screen in the wireless LAN, please try using the wired LAN.

**Comment by msbasanth** [comment]
Thanks for the quick reply. I will check.
