### ISSUE TITLE
AppRTCMobile was customized ? 

### ISSUE THREAD

**Issue by leofds** [kclyu/rpi-webrtc-streamer#62]
Hello,
AppRTCMobile has customized by you to work with the project?
I have not found the AppRTCMobile project for Android Studio ...
Can you guide me on how to compile ?

**Comment by kclyu** [comment]
Previously, Client Certificate related fixes were added. However, the function is not used, but it is the same as having no AppRTCMobile modification. In RWS, DirectSocket on Android AppRTCMobile seems to be available.
As you probably already know, I use to compile AppRTCMobile using this [Android Guide](https://webrtc.org/native-code/android/)  guide.
