### ISSUE TITLE
Launch android app from command line with default ip/room

### ISSUE THREAD

**Issue by blademckain** [kclyu/rpi-webrtc-streamer#80]
Hi,

it is possible to launch the android application by setting the ip / url /roomname to connect to as a parameter?
So you can connect directly to a specific server and room ?
something like:
org.appspot.apprtc: https: //myip/myroom

?

**Comment by kclyu** [comment]
There are no android app that work with rws yet. It only supports the function to work with DirectRTC of Android App. Although it has been the same in the past as AppRTC, it is no longer supported because it is too complicated for users to make an AppRTC-like environment.
