### ISSUE TITLE
How to set it up so that it can be streamed outside private network?

### ISSUE THREAD

**Issue by kennethjiang** [kclyu/rpi-webrtc-streamer#82]
First of all, awesome job on this project. Works seamlessly for me!

This is not an issue but a question. Feel free to close this issue and send me email: kenneth dot jiang [at] gmail dot com.

I'm trying to figure out how I can access WebRTC when I'm not on the same private network as the Pi. Basically I want to view the webcam stream on my phone while I'm not home. And I don't do it using port forwarding or VPN.

I have a feeling that I need to move the websocket part to a server in the cloud. But I'm really rusty with C++. Will really appreciate it if you can give me some hints on how this can be done. Or at least I want to know how difficult it'll be.

Thanks a lot!  - Kenneth

**Comment by kclyu** [comment]
If the router on your network supports VPN, you can connect directly to RWS. There are several advantages to using VPN,  you do not have to develop or configure complex system for security problems and user authentication. I recommend using VPN first. 

If you do not have VPN enabled environment, you can use Client Certificate and Reverse Proxy to connect Websoket to each RWS.

If you can develop and use it, I recommend that you develop a frontend that can use https such as rpi-webrtc-streamer-frontend and a proxy that mediates connection between each rws in the internal network. There are some people who use the structure similar to rpi-webrtc-streamer-frontend.
