### ISSUE TITLE
Current WebRTC commit?

### ISSUE THREAD

**Issue by psmitty7373** [kclyu/rpi-webrtc-streamer#84]
Are you still using '4d22a6d8dbb1db1f459338c14f8c6d814c6c9678' as the current commit when building your source?  I could not get that commit to work on RPI2/3 and had to use a later  version due to changes in the decode function.  I have not found a working commit for RPI Zero W.

**Comment by kclyu** [comment]
The commit currently used by master is a0421d3d0cd7fac9e178900cbd59f5a2006615a2.
