### ISSUE TITLE
WebRTC pffft compile error when building for armv6

### ISSUE THREAD

**Issue by psmitty7373** [kclyu/rpi-webrtc-streamer#85]
Building on on the Pi Zero W platform needed the flag -DPFFFT_SIMD_DISABLE to prevent NEON instructions in the PFFFT build.  Building errored other wise.

**Comment by kclyu** [comment]
native code developers are going to ignore armv6 little by little. In fact, chrome and android do not have armv6-enabled devices, so these compilation errors will occasionally occur.

Please modify //third_party/pffft/BUILD.gn as shown below.

```diff
*** BUILD.gn.orig	2019-05-03 12:55:33.474250583 +0900
--- BUILD.gn	2019-05-03 13:30:00.144457797 +0900
***************
*** 4,9 ****
--- 4,10 ----
  
  import("//testing/libfuzzer/fuzzer_test.gni")
  import("//testing/test.gni")
+ import("//build/config/arm.gni")
  
  config("common_config") {
    if (is_win) {
***************
*** 20,25 ****
--- 21,31 ----
      "src/pffft.c",
      "src/pffft.h",
    ]
+   if ( arm_arch == "armv6" ) {
+     cflags = [
+       "-DPFFFT_SIMD_DISABLE"
+     ]
+   }
  }
  
  # Fuzzing.
```
