### ISSUE TITLE
RWS and RWS-frontend encryption

### ISSUE THREAD

**Issue by kentloog** [kclyu/rpi-webrtc-streamer#87]
Hello @kclyu , 

Is the command of starting the video stream in RWS-frontend somehow encrytped? If yes, then how?

How does the messaging work when pressing "Connect" button?

**Comment by kentloog** [comment]
Okay, as i understand, the "messaging" goes through firebase realtime database and both web app and proxy on rpi listen to updates in the database. Am i right? @kclyu

**Comment by kclyu** [comment]
The message transfer flow used in firebase-frontend is exactly what you are talking about.
