### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by drewcovi** [kclyu/rpi-webrtc-streamer#88]
Is the only way to get the latest build of this project to cross compile in ubuntu?

If so any chance we can get an update to the debian packages?

**Comment by kclyu** [comment]
If RWS fps issue is confirmed to be stabilized to some extent, I will update RWS deb package. But it will take a little more time. If you want to use the latest binaries before the deb package is updated, you can either use cross compile on Ubuntu or use the docker file in the current pull request.

**Comment by drewcovi** [comment]
wait, there's a docker?! ❤️ ❤️ ❤️ ❤️
