### ISSUE TITLE
Vertical white line in video

### ISSUE THREAD

**Issue by leofds** [kclyu/rpi-webrtc-streamer#90]
Hi Lyu,
Changing the background color of the "native-peerconnection" example I can see a vertical white line on the right of the video.

![Screenshot from 2019-07-11 09-44-11](https://user-images.githubusercontent.com/5174326/61173996-fcefb980-a570-11e9-8cee-ca46a9d8cf04.png)

This does not occur using the raspistill command to take a picture.
Is this just with me ? How can I solve this ?

**Comment by ronb127** [comment]
See: https://www.raspberrypi.org/forums/viewtopic.php?t=227701
It is a problem with raspberry pi's camera default ROI.
You can solve it by shrinking the ROI (add somewhere in mmal_video.c):

PARAM_FLOAT_RECT_T roi = {0.0, 0.0, 0.998, 1.0};
raspicamcontrol_set_ROI(camera->output[0], &roi);

**Comment by leofds** [comment]
Thanks, I will close this issue because I can't test at the moment.
