### ISSUE TITLE
Browser mic to Rpi speaker

### ISSUE THREAD

**Issue by natriumlamp** [kclyu/rpi-webrtc-streamer#91]
Hello I am trying to make a two way audio streaming system with this wonderful low delay tool. 

I have followed the instruction to make Rpi to Browser audio streaming possible but Browser mic to Rpi speaker, I can't find the way to make it.

Can it be done by changing and modifying the JavaScript contents inside /opt/rws/web-root or should I rebuild the webrtc-streamer binary?

Also, I want to implement video&audio stream recording that file will be saved in local Rpi. Is rebuild needed for this?

Thanks.

**Comment by jonspieg** [comment]
@natriumlamp did you manage to stream audio from the browser to RWS?

**Comment by natriumlamp** [comment]
> @natriumlamp did you manage to stream audio from the browser to RWS?

There might be a way but unfortunately I didn't.
I gave up making one.
