### ISSUE TITLE
Capture image frames in hi resolution with raspistill or other solution.

### ISSUE THREAD

**Issue by intercoleco** [kclyu/rpi-webrtc-streamer#96]
Dear Lyu Keun Chang, thanks for your work!

I need know a way for capture images in full hi resolution (not snapshot) , at same time when view the real time streaming, like use raspistill.

Or a way for pause streaming process, capture with raspistill or other program, and continues with streaming.

Any solution, idea or code?

**Comment by kclyu** [comment]
There is currently no way to capture hi resolution still image during RTC streaming. RWS uses a method to dynamically change the video camera resolution setting according to the bandwidth.

I am trying to implement the still image capture function. However, I also plan to capture periodically before streaming, but I will not try to do it in the middle of streaming.

There is a way to do it while streaming, but it has to be complicated by the spllitter/resizer functions internally. I wonder if there is a reason you really need it.
